project:
  type: website

website:
  title: "Dynamic Data Dojo"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo